name: Test Node CLI Tool

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout code
                uses: actions/checkout@v3

            # Set up Node.js
            - name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '16' # Specify the Node.js version

            # Set up Java 17
            - name: Set up Java 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin' # Use Eclipse Temurin distribution
                    java-version: '17'

            # Install dependencies
            - name: Install dependencies
                run: npm install

            # Run ESLint
            - name: Run ESLint
                run: npx eslint .

            # Run tests
            - name: Run tests
                run: npm test

            # Test the CLI tool
            - name: Test CLI tool
                run: |
                    node ./path-to-your-cli-tool.js --help
                    node ./path-to-your-cli-tool.js some-command